import "./globals.css";
import { Inter, Space_Mono } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });
const space_mono = Space_Mono({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-space-mono",
  weight: "400",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${space_mono.variable}`}>
        {children}
      </body>
    </html>
  );
}
